# Generated by Django 5.1.6 on 2025-02-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelloPosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto1', models.CharField(max_length=30)),
                ('posto2', models.CharField(max_length=30)),
                ('posto3', models.CharField(max_length=30)),
                ('posto4', models.CharField(max_length=30)),
                ('posto5', models.CharField(max_length=30)),
                ('posto6', models.CharField(max_length=30)),
                ('posto7', models.CharField(max_length=30)),
                ('posto8', models.CharField(max_length=30)),
                ('posto9', models.CharField(max_length=30)),
                ('posto10', models.CharField(max_length=30)),
                ('posto11', models.CharField(max_length=30)),
                ('posto12', models.CharField(max_length=30)),
                ('posto13', models.CharField(max_length=30)),
                ('posto14', models.CharField(max_length=30)),
                ('posto15', models.CharField(max_length=30)),
                ('posto16', models.CharField(max_length=30)),
                ('posto17', models.CharField(max_length=30)),
                ('posto18', models.CharField(max_length=30)),
                ('posto19', models.CharField(max_length=30)),
                ('posto20', models.CharField(max_length=30)),
                ('posto21', models.CharField(max_length=30)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
